server:
  port: 4000
spring:
  resources:
    static-locations:
    - file:./${_site.static_html}/
    - file:./static/
  freemarker:
    template-loader-path:
    - file:./templates/
    - classpath:/templates/

_site:
  debug: false
  title: Tomoya's Blog
  subTitle: Code, Animation
  description: Record my learning notes
  author: tomoya
  theme: default
  url: http://localhost:4000
  permaLink: /:year/:month/:day/:title/
  excerptSeparator: "\n\n\n\n"
  pageSize: 10
  post: ./_posts
  staticHtml: ./_sites
#  links:
#    Github: https://github.com/
#    Google: https://google.com/
#  contacts:
#    email:
#    github:
#    weibo:
#  analytics:
#    baidu:
#    google:
#  comment:
#    changyan:
#    disqus:
#  other:
