server:
  port: 4000
spring:
  resources:
    static-locations:
    - file:./_site/
    - file:./static/
  freemarker:
    template-loader-path:
    - file:./templates/
    - classpath:/templates/

_site:
  debug: false
  theme: default
  url: http://localhost:4000
  page_size: 10
  title: Tomoya
  brief_intro: Code, Animation
  permalink: /:year/:month/:day/:title/
  description_footer: Hello World!
  excerpt_separator: "\n\n\n\n"
#  links:
#    Github: https://github.com/
#    Google: https://google.com/
#  contacts:
#    email:
#    github:
#    weibo:
#  analytics:
#    baidu:
#    google:
#  comment:
#    changyan:
#    disqus:
  post: ./_posts
  static_html: ./_site
