server:
  port: 4000
spring:
  resources:
    static-locations:
    - file:./${_site.static_html}/
    - file:./static/
  freemarker:
    template-loader-path:
    - file:./templates/
    - classpath:/templates/

_site:
  debug: false
  theme: default
  url: http://localhost:4000
  permalink: /:year/:month/:day/:title/
  excerpt_separator: "\n\n\n\n"
  page_size: 10
  post: ./_posts
  static_html: ./_sites
  base:
    title: Tomoya
    brief_intro: Code, Animation
    description_footer: Hello World!
#  links:
#    Github: https://github.com/
#    Google: https://google.com/
#  contacts:
#    email:
#    github:
#    weibo:
#  analytics:
#    baidu:
#    google:
#  comment:
#    changyan:
#    disqus:
